.\" Manpage for mystrlen (section 3)
.TH mystrlen 3 "October 2025" "myutils 0.1"
.SH NAME
mystrlen \- return length of a string

.SH SYNOPSIS
.B int mystrlen(const char *s)

.SH DESCRIPTION
mystrlen calculates and returns the length of the null-terminated string pointed to by \fIs\fP.
It behaves similarly to the standard strlen function.

.SH RETURN VALUE
Returns the number of characters preceding the terminating null byte.

.SH AUTHOR
muhammad siyyam <siyyam461@gmail.com>
