.\" Manpage for client (section 1)
.TH client 1 "October 2025" "client 0.1"
.SH NAME
client \- simple test client for myutils library

.SH SYNOPSIS
.B client
.RI [ options ]

.SH DESCRIPTION
client runs a suite of simple tests for the myutils library: string functions and file functions.
It is built as part of the project and can be run to exercise library features.

.SH OPTIONS
No command line options are currently required.

.SH AUTHOR
muhammad siyyam <siyyam461@gmail.com>
